// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.learn.domain;

import com.rahul.learn.domain.Cart;
import com.rahul.learn.domain.CartDataOnDemand;
import com.rahul.learn.service.CartService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CartDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CartDataOnDemand: @Component;
    
    private Random CartDataOnDemand.rnd = new SecureRandom();
    
    private List<Cart> CartDataOnDemand.data;
    
    @Autowired
    CartService CartDataOnDemand.cartService;
    
    public Cart CartDataOnDemand.getNewTransientCart(int index) {
        Cart obj = new Cart();
        return obj;
    }
    
    public Cart CartDataOnDemand.getSpecificCart(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cart obj = data.get(index);
        BigInteger id = obj.getId();
        return cartService.findCart(id);
    }
    
    public Cart CartDataOnDemand.getRandomCart() {
        init();
        Cart obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return cartService.findCart(id);
    }
    
    public boolean CartDataOnDemand.modifyCart(Cart obj) {
        return false;
    }
    
    public void CartDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = cartService.findCartEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cart' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cart>();
        for (int i = 0; i < 10; i++) {
            Cart obj = getNewTransientCart(i);
            try {
                cartService.saveCart(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
