// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.learn.domain;

import com.rahul.learn.domain.CartDataOnDemand;
import com.rahul.learn.domain.CartIntegrationTest;
import com.rahul.learn.service.CartService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect CartIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CartIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CartIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private CartDataOnDemand CartIntegrationTest.dod;
    
    @Autowired
    CartService CartIntegrationTest.cartService;
    
    @Test
    public void CartIntegrationTest.testCountAllCarts() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        long count = cartService.countAllCarts();
        Assert.assertTrue("Counter for 'Cart' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CartIntegrationTest.testFindCart() {
        Cart obj = dod.getRandomCart();
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide an identifier", id);
        obj = cartService.findCart(id);
        Assert.assertNotNull("Find method for 'Cart' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cart' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CartIntegrationTest.testFindAllCarts() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        long count = cartService.countAllCarts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cart', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cart> result = cartService.findAllCarts();
        Assert.assertNotNull("Find all method for 'Cart' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cart' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CartIntegrationTest.testFindCartEntries() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        long count = cartService.countAllCarts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cart> result = cartService.findCartEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Cart' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cart' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CartIntegrationTest.testSaveCart() {
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", dod.getRandomCart());
        Cart obj = dod.getNewTransientCart(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cart' identifier to be null", obj.getId());
        cartService.saveCart(obj);
        Assert.assertNotNull("Expected 'Cart' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CartIntegrationTest.testDeleteCart() {
        Cart obj = dod.getRandomCart();
        Assert.assertNotNull("Data on demand for 'Cart' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cart' failed to provide an identifier", id);
        obj = cartService.findCart(id);
        cartService.deleteCart(obj);
        Assert.assertNull("Failed to remove 'Cart' with identifier '" + id + "'", cartService.findCart(id));
    }
    
}
