// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.learn.domain;

import com.rahul.learn.domain.CartDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CartDataOnDemand_Roo_Configurable {
    
    declare @type: CartDataOnDemand: @Configurable;
    
}
