// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.learn.domain;

import com.rahul.learn.domain.ItemDataOnDemand;
import com.rahul.learn.domain.ItemIntegrationTest;
import com.rahul.learn.service.ItemService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect ItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private ItemDataOnDemand ItemIntegrationTest.dod;
    
    @Autowired
    ItemService ItemIntegrationTest.itemService;
    
    @Test
    public void ItemIntegrationTest.testCountAllItems() {
        Assert.assertNotNull("Data on demand for 'Item' failed to initialize correctly", dod.getRandomItem());
        long count = itemService.countAllItems();
        Assert.assertTrue("Counter for 'Item' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ItemIntegrationTest.testFindItem() {
        Item obj = dod.getRandomItem();
        Assert.assertNotNull("Data on demand for 'Item' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Item' failed to provide an identifier", id);
        obj = itemService.findItem(id);
        Assert.assertNotNull("Find method for 'Item' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Item' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ItemIntegrationTest.testFindAllItems() {
        Assert.assertNotNull("Data on demand for 'Item' failed to initialize correctly", dod.getRandomItem());
        long count = itemService.countAllItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'Item', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Item> result = itemService.findAllItems();
        Assert.assertNotNull("Find all method for 'Item' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Item' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ItemIntegrationTest.testFindItemEntries() {
        Assert.assertNotNull("Data on demand for 'Item' failed to initialize correctly", dod.getRandomItem());
        long count = itemService.countAllItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Item> result = itemService.findItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Item' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Item' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ItemIntegrationTest.testSaveItem() {
        Assert.assertNotNull("Data on demand for 'Item' failed to initialize correctly", dod.getRandomItem());
        Item obj = dod.getNewTransientItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Item' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Item' identifier to be null", obj.getId());
        itemService.saveItem(obj);
        Assert.assertNotNull("Expected 'Item' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ItemIntegrationTest.testDeleteItem() {
        Item obj = dod.getRandomItem();
        Assert.assertNotNull("Data on demand for 'Item' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Item' failed to provide an identifier", id);
        obj = itemService.findItem(id);
        itemService.deleteItem(obj);
        Assert.assertNull("Failed to remove 'Item' with identifier '" + id + "'", itemService.findItem(id));
    }
    
}
